// Package generate emits allocation-free language bindings from a resolved
// Exact32 manifest. Generated accessors contain constants, not schema tables.
package generate

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"strings"
	"unicode"

	"github.com/JairusSW/wago-bind-as/schema"
)

func Go(manifest schema.Manifest, packageName string) ([]byte, error) {
	if !identifier.MatchString(packageName) || token.IsKeyword(packageName) {
		return nil, fmt.Errorf("invalid Go package %q", packageName)
	}
	if err := validateGoNames(manifest); err != nil {
		return nil, err
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by wago-bind-as; DO NOT EDIT.\n\npackage %s\n\n", packageName)
	if len(manifest.Functions) == 0 {
		out.WriteString("import bindas \"github.com/JairusSW/wago-bind-as\"\n\n")
	} else {
		needsBinary, needsMath := facadeImportNeeds(manifest)
		out.WriteString("import (\n")
		if needsBinary {
			out.WriteString("\t\"encoding/binary\"\n")
		}
		out.WriteString("\t\"fmt\"\n")
		if needsMath {
			out.WriteString("\t\"math\"\n")
		}
		out.WriteString("\t\"sync\"\n\n\tbindas \"github.com/JairusSW/wago-bind-as\"\n\twago \"github.com/wago-org/wago\"\n)\n\n")
	}
	fingerprint, err := hex.DecodeString(manifest.Fingerprint)
	if err != nil || len(fingerprint) != 16 {
		return nil, fmt.Errorf("invalid manifest fingerprint %q", manifest.Fingerprint)
	}
	fmt.Fprintf(&out, "const SchemaFingerprintHex = %q\n\n", manifest.Fingerprint)
	fmt.Fprintf(&out, "func Fingerprint() bindas.Fingerprint { return bindas.Fingerprint{%s} }\n\n", goByteList(fingerprint))
	byName := make(map[string]schema.ResolvedType, len(manifest.Types))
	for _, typ := range manifest.Types {
		byName[typ.Name] = typ
	}
	for _, typ := range manifest.Types {
		name := exported(typ.Name)
		fmt.Fprintf(&out, "const (\n\t%sSize uint32 = %d\n\t%sAlign uint32 = %d\n)\n\n", name, typ.Size, name, typ.Align)
		fmt.Fprintf(&out, "type %sView struct { record bindas.Record }\n\n", name)
		fmt.Fprintf(&out, "func Open%s(region bindas.Region, offset bindas.Offset) (%sView, error) {\n\trecord, err := region.Record(offset, %sSize, %sAlign)\n\treturn %sView{record: record}, err\n}\n\n", name, name, name, name, name)
		fmt.Fprintf(&out, "func New%s(arena *bindas.Arena) (%sView, error) {\n\toffset, err := arena.Alloc(%sSize, %sAlign)\n\tif err != nil { return %sView{}, err }\n\treturn Open%s(arena.Region(), offset)\n}\n\n", name, name, name, name, name, name)
		fmt.Fprintf(&out, "func (v %sView) Offset() bindas.Offset { return v.record.Offset() }\n\n", name)
		for _, field := range typ.Fields {
			if err := emitGoField(&out, name, field, byName); err != nil {
				return nil, err
			}
		}
		if err := emitGoBuilder(&out, typ, byName); err != nil {
			return nil, err
		}
	}
	if len(manifest.Functions) != 0 {
		if err := emitGoModule(&out, manifest, byName, fingerprint); err != nil {
			return nil, err
		}
	}
	return format.Source(out.Bytes())
}

func facadeImportNeeds(manifest schema.Manifest) (binary, math bool) {
	used := make(map[string]struct{})
	for _, function := range manifest.Functions {
		for _, parameter := range function.Parameters {
			used[parameter.Type] = struct{}{}
		}
		if function.Result != "" {
			used[function.Result] = struct{}{}
		}
	}
	for _, typ := range manifest.Types {
		if _, ok := used[typ.Name]; !ok {
			continue
		}
		for _, field := range typ.Fields {
			switch field.Type {
			case "i16", "u16", "i32", "u32", "i64", "u64", "timestamp_ns", "duration_ns":
				binary = true
			case "f32", "f64":
				binary, math = true, true
			}
		}
	}
	return binary, math
}

func validateGoNames(manifest schema.Manifest) error {
	recordTypes := make(map[string]struct{}, len(manifest.Types))
	for _, typ := range manifest.Types {
		recordTypes[typ.Name] = struct{}{}
	}
	claimed := map[string]string{
		"SchemaFingerprintHex": "schema fingerprint constant",
		"Fingerprint":          "schema fingerprint function",
	}
	claim := func(identifier, source string) error {
		if previous, exists := claimed[identifier]; exists {
			return fmt.Errorf("generated Go identifier %q for %s conflicts with %s", identifier, source, previous)
		}
		claimed[identifier] = source
		return nil
	}
	for _, typ := range manifest.Types {
		name := exported(typ.Name)
		for _, identifier := range []string{name, name + "View", name + "Input", name + "Size", name + "Align", "Open" + name, "New" + name, "Build" + name, "fill" + name} {
			if err := claim(identifier, "type "+typ.Name); err != nil {
				return err
			}
		}
		fields := make(map[string]string, len(typ.Fields))
		methods := map[string]string{"Offset": "generated offset accessor"}
		for _, field := range typ.Fields {
			name := exported(field.Name)
			if previous, exists := fields[name]; exists {
				return fmt.Errorf("generated Go field %q in %s conflicts with field %s", name, typ.Name, previous)
			}
			fields[name] = field.Name
			fieldMethods := []string{name}
			if _, _, scalar := scalar(field.Type); scalar {
				fieldMethods = append(fieldMethods, "Set"+name)
			} else {
				switch field.Type {
				case "utf8":
					fieldMethods = append(fieldMethods, "Set"+name, name+"UTF8", "Set"+name+"String")
				case "bytes":
					fieldMethods = append(fieldMethods, "Set"+name, "Set"+name+"Bytes")
				case "uuid", "digest256":
					fieldMethods = append(fieldMethods, "Mutable"+name)
				default:
					if inner, vector := wrapped(field.Type, "vec"); vector {
						fieldMethods = append(fieldMethods, "Reserve"+name)
						if _, record := recordTypes[inner]; record {
							fieldMethods = append(fieldMethods, name+"At", "Append"+name)
						}
					} else if _, reference := wrapped(field.Type, "ref"); reference {
						fieldMethods = append(fieldMethods, "Set"+name)
					} else if strings.HasPrefix(field.Type, "array<") {
						fieldMethods = append(fieldMethods, "Mutable"+name)
					}
				}
			}
			for _, method := range fieldMethods {
				if previous, exists := methods[method]; exists {
					return fmt.Errorf("generated Go method %q in %s for field %s conflicts with %s", method, typ.Name, field.Name, previous)
				}
				methods[method] = "field " + field.Name
			}
		}
	}
	functions := make(map[string]string, len(manifest.Functions))
	for _, function := range manifest.Functions {
		name := exported(function.Name)
		if previous, exists := functions[name]; exists {
			return fmt.Errorf("generated Go method %q for function %s conflicts with function %s", name, function.Name, previous)
		}
		functions[name] = function.Name
	}
	return nil
}

func emitGoBuilder(out *bytes.Buffer, typ schema.ResolvedType, types map[string]schema.ResolvedType) error {
	name := exported(typ.Name)
	fmt.Fprintf(out, "type %s struct {\n", name)
	for _, field := range typ.Fields {
		inputType, err := goInputType(field.Type, types)
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "\t%s %s\n", exported(field.Name), inputType)
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(out, "type %sInput = %s\n\n", name, name)
	fmt.Fprintf(out, "func Build%s(arena *bindas.Arena, value %sInput) (%sView, error) {\n\tcheckpoint := arena.Checkpoint()\n\tview, err := New%s(arena)\n\tif err != nil { return %sView{}, err }\n\tif err = fill%s(arena, view, value); err != nil { _ = arena.Rollback(checkpoint); return %sView{}, err }\n\treturn view, nil\n}\n\n", name, name, name, name, name, name, name)
	fmt.Fprintf(out, "func fill%s(arena *bindas.Arena, view %sView, value %sInput) error {\n", name, name, name)
	for _, field := range typ.Fields {
		if err := emitGoBuilderField(out, field, types); err != nil {
			return err
		}
	}
	out.WriteString("\treturn nil\n}\n\n")
	return nil
}

func emitGoModule(out *bytes.Buffer, manifest schema.Manifest, types map[string]schema.ResolvedType, fingerprint []byte) error {
	for _, function := range manifest.Functions {
		maxParameters := 4
		if function.Result != "" {
			maxParameters = 3 // the generated call plan passes reusable result storage as the final argument
		}
		if len(function.Parameters) > maxParameters {
			return fmt.Errorf("function %s has %d parameters; the allocation-free facade supports at most %d for this signature", function.Name, len(function.Parameters), maxParameters)
		}
		for _, parameter := range function.Parameters {
			if err := requireScalarRecord(types[parameter.Type]); err != nil {
				return fmt.Errorf("function %s parameter %s: %w", function.Name, parameter.Name, err)
			}
		}
		if function.Result != "" {
			if err := requireScalarRecord(types[function.Result]); err != nil {
				return fmt.Errorf("function %s result: %w", function.Name, err)
			}
		}
	}

	out.WriteString("type Module struct {\n\tmu sync.Mutex\n\tmemory *wago.Memory\n")
	for _, function := range manifest.Functions {
		name := exported(function.Name)
		fmt.Fprintf(out, "\t%s *wago.PreparedFunction\n", unexported(name))
		if len(function.Parameters) != 0 {
			fmt.Fprintf(out, "\t%sArgs [%d]uint32\n", unexported(name), len(function.Parameters))
		}
		if function.Result != "" {
			fmt.Fprintf(out, "\t%sResult uint32\n", unexported(name))
		}
	}
	out.WriteString("}\n\n")
	out.WriteString("func Bind(instance *wago.Instance) (*Module, error) {\n")
	out.WriteString("\tif instance == nil { return nil, fmt.Errorf(\"wago-bind-as: nil Wago instance\") }\n")
	out.WriteString("\tmemory := instance.Memory(); if memory == nil { return nil, fmt.Errorf(\"wago-bind-as: instance has no memory zero\") }\n")
	out.WriteString("\tabi0, err := instance.PrepareFunction(\"__wbas_abi_0\"); if err != nil { return nil, err }\n")
	out.WriteString("\tabi1, err := instance.PrepareFunction(\"__wbas_abi_1\"); if err != nil { return nil, err }\n")
	fmt.Fprintf(out, "\twant0, want1 := uint64(0x%016x), uint64(0x%016x)\n", binary.LittleEndian.Uint64(fingerprint[:8]), binary.LittleEndian.Uint64(fingerprint[8:]))
	out.WriteString("\tgot0, err := abi0.Invoke0(); if err != nil { return nil, err }; if len(got0) != 1 { return nil, fmt.Errorf(\"wago-bind-as: ABI fingerprint export 0 returned the wrong arity\") }; actual0 := got0[0]\n")
	out.WriteString("\tgot1, err := abi1.Invoke0(); if err != nil { return nil, err }; if len(got1) != 1 { return nil, fmt.Errorf(\"wago-bind-as: ABI fingerprint export 1 returned the wrong arity\") }; actual1 := got1[0]\n")
	out.WriteString("\tif actual0 != want0 || actual1 != want1 { return nil, fmt.Errorf(\"wago-bind-as: ABI fingerprint mismatch: Go expects %016x%016x, Wasm returned %016x%016x\", want0, want1, actual0, actual1) }\n")
	out.WriteString("\tallocate, err := instance.PrepareFunction(\"__wbas_alloc\"); if err != nil { return nil, err }\n")
	out.WriteString("\tmodule := &Module{memory: memory}\n")
	for _, function := range manifest.Functions {
		name, field := exported(function.Name), unexported(exported(function.Name))
		exportName := function.Name
		if function.Result != "" {
			exportName = "__wbas_call_" + function.Name
		}
		fmt.Fprintf(out, "\tmodule.%s, err = instance.PrepareFunction(%q); if err != nil { return nil, err }\n", field, exportName)
		for i, parameter := range function.Parameters {
			typ := types[parameter.Type]
			fmt.Fprintf(out, "\t%sArg%d, err := allocate.Invoke1(uint64(%sSize)); if err != nil { return nil, err }; if len(%sArg%d) != 1 || uint64(uint32(%sArg%d[0])) != %sArg%d[0] { return nil, fmt.Errorf(\"wago-bind-as: allocator returned an invalid pointer for %s argument %d\") }; module.%sArgs[%d] = uint32(%sArg%d[0])\n", field, i, exported(typ.Name), field, i, field, i, field, i, name, i, field, i, field, i)
		}
		if function.Result != "" {
			typ := types[function.Result]
			fmt.Fprintf(out, "\t%sResult, err := allocate.Invoke1(uint64(%sSize)); if err != nil { return nil, err }; if len(%sResult) != 1 || uint64(uint32(%sResult[0])) != %sResult[0] { return nil, fmt.Errorf(\"wago-bind-as: allocator returned an invalid pointer for %s result\") }; module.%sResult = uint32(%sResult[0])\n", field, exported(typ.Name), field, field, field, name, field, field)
		}
	}
	out.WriteString("\treturn module, nil\n}\n\n")

	usedTypes := make(map[string]struct{})
	for _, function := range manifest.Functions {
		for _, parameter := range function.Parameters {
			usedTypes[parameter.Type] = struct{}{}
		}
		if function.Result != "" {
			usedTypes[function.Result] = struct{}{}
		}
	}
	for _, typ := range manifest.Types {
		if _, used := usedTypes[typ.Name]; !used {
			continue
		}
		emitScalarRecordIO(out, typ)
	}
	for _, function := range manifest.Functions {
		emitGoFunction(out, function)
	}
	return nil
}

func requireScalarRecord(typ schema.ResolvedType) error {
	if typ.Name == "" {
		return fmt.Errorf("unknown record")
	}
	for _, field := range typ.Fields {
		if _, _, ok := scalar(field.Type); !ok {
			return fmt.Errorf("record %s contains non-scalar field %s", typ.Name, field.Name)
		}
	}
	return nil
}

func emitScalarRecordIO(out *bytes.Buffer, typ schema.ResolvedType) {
	name := exported(typ.Name)
	fmt.Fprintf(out, "func write%s(memory []byte, address uint32, value %s) error {\n", name, name)
	fmt.Fprintf(out, "\tif uint64(address) + uint64(%sSize) > uint64(len(memory)) { return bindas.ErrBounds }\n", name)
	for _, field := range typ.Fields {
		emitScalarWrite(out, field, "value."+exported(field.Name))
	}
	out.WriteString("\treturn nil\n}\n\n")
	fmt.Fprintf(out, "func read%s(memory []byte, address uint32) (%s, error) {\n", name, name)
	fmt.Fprintf(out, "\tif uint64(address) + uint64(%sSize) > uint64(len(memory)) { return %s{}, bindas.ErrBounds }; var value %s\n", name, name, name)
	for _, field := range typ.Fields {
		emitScalarRead(out, field, "value."+exported(field.Name), name)
	}
	out.WriteString("\treturn value, nil\n}\n\n")
}

func emitScalarWrite(out *bytes.Buffer, field schema.ResolvedField, value string) {
	address := fmt.Sprintf("address + %d", field.Offset)
	switch field.Type {
	case "bool":
		fmt.Fprintf(out, "\tif %s { memory[%s] = 1 } else { memory[%s] = 0 }\n", value, address, address)
	case "i8", "u8":
		fmt.Fprintf(out, "\tmemory[%s] = byte(%s)\n", address, value)
	case "i16", "u16":
		fmt.Fprintf(out, "\tbinary.LittleEndian.PutUint16(memory[%s:], uint16(%s))\n", address, value)
	case "i32", "u32":
		fmt.Fprintf(out, "\tbinary.LittleEndian.PutUint32(memory[%s:], uint32(%s))\n", address, value)
	case "i64", "u64", "timestamp_ns", "duration_ns":
		fmt.Fprintf(out, "\tbinary.LittleEndian.PutUint64(memory[%s:], uint64(%s))\n", address, value)
	case "f32":
		fmt.Fprintf(out, "\tbinary.LittleEndian.PutUint32(memory[%s:], math.Float32bits(%s))\n", address, value)
	case "f64":
		fmt.Fprintf(out, "\tbinary.LittleEndian.PutUint64(memory[%s:], math.Float64bits(%s))\n", address, value)
	}
}

func emitScalarRead(out *bytes.Buffer, field schema.ResolvedField, target, record string) {
	address := fmt.Sprintf("address + %d", field.Offset)
	switch field.Type {
	case "bool":
		fmt.Fprintf(out, "\tif memory[%s] > 1 { return %s{}, bindas.ErrMalformed }; %s = memory[%s] != 0\n", address, record, target, address)
	case "i8", "u8":
		fmt.Fprintf(out, "\t%s = %s(memory[%s])\n", target, scalarGoType(field.Type), address)
	case "i16", "u16":
		fmt.Fprintf(out, "\t%s = %s(binary.LittleEndian.Uint16(memory[%s:]))\n", target, scalarGoType(field.Type), address)
	case "i32", "u32":
		fmt.Fprintf(out, "\t%s = %s(binary.LittleEndian.Uint32(memory[%s:]))\n", target, scalarGoType(field.Type), address)
	case "i64", "u64", "timestamp_ns", "duration_ns":
		fmt.Fprintf(out, "\t%s = %s(binary.LittleEndian.Uint64(memory[%s:]))\n", target, scalarGoType(field.Type), address)
	case "f32":
		fmt.Fprintf(out, "\t%s = math.Float32frombits(binary.LittleEndian.Uint32(memory[%s:]))\n", target, address)
	case "f64":
		fmt.Fprintf(out, "\t%s = math.Float64frombits(binary.LittleEndian.Uint64(memory[%s:]))\n", target, address)
	}
}

func scalarGoType(value string) string {
	typ, _, _ := scalar(value)
	return typ
}

func emitGoFunction(out *bytes.Buffer, function schema.ResolvedFunction) {
	name, field := exported(function.Name), unexported(exported(function.Name))
	fmt.Fprintf(out, "func (m *Module) %s(", name)
	for i, parameter := range function.Parameters {
		if i != 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "arg%d %s", i, exported(parameter.Type))
	}
	if function.Result == "" {
		out.WriteString(") error {\n")
	} else {
		fmt.Fprintf(out, ") (%s, error) {\n", exported(function.Result))
	}
	if function.Result == "" {
		out.WriteString("\tif m == nil { return fmt.Errorf(\"wago-bind-as: nil module\") }\n")
	} else {
		fmt.Fprintf(out, "\tif m == nil { return %s{}, fmt.Errorf(\"wago-bind-as: nil module\") }\n", exported(function.Result))
	}
	out.WriteString("\tm.mu.Lock(); defer m.mu.Unlock(); memory := m.memory.UnsafeBytes()\n")
	if function.Result == "" {
		out.WriteString("\tif memory == nil { return fmt.Errorf(\"wago-bind-as: memory is closed\") }\n")
	} else {
		fmt.Fprintf(out, "\tif memory == nil { return %s{}, fmt.Errorf(\"wago-bind-as: memory is closed\") }\n", exported(function.Result))
	}
	for i, parameter := range function.Parameters {
		if function.Result == "" {
			fmt.Fprintf(out, "\tif err := write%s(memory, m.%sArgs[%d], arg%d); err != nil { return err }\n", exported(parameter.Type), field, i, i)
		} else {
			fmt.Fprintf(out, "\tif err := write%s(memory, m.%sArgs[%d], arg%d); err != nil { return %s{}, err }\n", exported(parameter.Type), field, i, i, exported(function.Result))
		}
	}
	argumentCount := len(function.Parameters)
	if function.Result != "" {
		argumentCount++
	}
	fmt.Fprintf(out, "\tresults, err := m.%s.Invoke%d(", field, argumentCount)
	for i := range function.Parameters {
		if i != 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "uint64(m.%sArgs[%d])", field, i)
	}
	if function.Result != "" {
		if len(function.Parameters) != 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "uint64(m.%sResult)", field)
	}
	out.WriteString(")\n")
	if function.Result == "" {
		out.WriteString("\treturn err\n}\n\n")
	} else {
		result := exported(function.Result)
		fmt.Fprintf(out, "\tif err != nil { return %s{}, err }; if len(results) != 0 { return %s{}, fmt.Errorf(\"wago-bind-as: invalid %s result arity\") }; memory = m.memory.UnsafeBytes(); if memory == nil { return %s{}, fmt.Errorf(\"wago-bind-as: memory is closed\") }; value, readErr := read%s(memory, m.%sResult)\n", result, result, function.Name, result, result, field)
		fmt.Fprintf(out, "\tif readErr != nil { return %s{}, readErr }; return value, nil\n}\n\n", result)
	}
}

func unexported(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func emitGoBuilderField(out *bytes.Buffer, field schema.ResolvedField, types map[string]schema.ResolvedType) error {
	name := exported(field.Name)
	value := "value." + name
	if _, _, ok := scalar(field.Type); ok {
		fmt.Fprintf(out, "\tif err := view.Set%s(%s); err != nil { return err }\n", name, value)
		return nil
	}
	switch field.Type {
	case "utf8":
		fmt.Fprintf(out, "\tif err := view.Set%sString(arena, %s); err != nil { return err }\n", name, value)
		return nil
	case "bytes":
		fmt.Fprintf(out, "\tif err := view.Set%sBytes(arena, %s); err != nil { return err }\n", name, value)
		return nil
	case "uuid", "digest256":
		fmt.Fprintf(out, "\tdestination%s, err := view.Mutable%s(); if err != nil { return err }; copy(destination%s, %s[:])\n", name, name, name, value)
		return nil
	}
	if inner, ok := wrapped(field.Type, "ref"); ok {
		fmt.Fprintf(out, "\tif %s == nil { return bindas.ErrMalformed }\n", value)
		fmt.Fprintf(out, "\t%sValue, err := Build%s(arena, *%s); if err != nil { return err }; if err = view.Set%s(%sValue); err != nil { return err }\n", field.Name, exported(inner), value, name, field.Name)
		return nil
	}
	if inner, ok := wrapped(field.Type, "vec"); ok {
		shape, exists := generatorShape(inner, types)
		if !exists {
			return fmt.Errorf("unknown vector element %q", inner)
		}
		fmt.Fprintf(out, "\tif uint64(len(%s)) > uint64(^uint32(0)) { return bindas.ErrOutOfSpace }\n", value)
		fmt.Fprintf(out, "\t%sVector, err := view.Reserve%s(arena, uint32(len(%s))); if err != nil { return err }\n", field.Name, name, value)
		fmt.Fprintf(out, "\tfor _, item := range %s { record, err := %sVector.Append(); if err != nil { return err }; ", value, field.Name)
		if _, record := types[inner]; record {
			fmt.Fprintf(out, "if err = fill%s(arena, %sView{record: record}, item); err != nil { return err }", exported(inner), exported(inner))
		} else if inner == "utf8" || inner == "bytes" {
			put := "PutBytes(item, 1)"
			if inner == "utf8" {
				put = "PutUTF8(item)"
			}
			fmt.Fprintf(out, "span, err := arena.%s; if err != nil { return err }; if err = record.SetRegionSpan(0, span); err != nil { return err }", put)
		} else if _, method, scalarType := scalar(inner); scalarType {
			fmt.Fprintf(out, "if err = record.Set%s(0, item); err != nil { return err }", method)
		} else {
			return fmt.Errorf("unsupported vector element %q with size %d", inner, shape.Size)
		}
		out.WriteString(" }\n")
		return nil
	}
	if nested, exists := types[field.Type]; exists {
		fmt.Fprintf(out, "\t%sView, err := view.%s(arena.Region()); if err != nil { return err }; if err = fill%s(arena, %sView, %s); err != nil { return err }\n", field.Name, name, exported(nested.Name), field.Name, value)
		return nil
	}
	if strings.HasPrefix(field.Type, "array<") {
		fmt.Fprintf(out, "\tif len(%s) != %d { return bindas.ErrMalformed }\n", value, field.Size)
		fmt.Fprintf(out, "\tdestination%s, err := view.Mutable%s(); if err != nil { return err }; copy(destination%s, %s)\n", name, name, name, value)
		return nil
	}
	return fmt.Errorf("unsupported builder field type %q", field.Type)
}

func goInputType(value string, types map[string]schema.ResolvedType) (string, error) {
	if goType, _, ok := scalar(value); ok {
		return goType, nil
	}
	switch value {
	case "utf8":
		return "string", nil
	case "bytes":
		return "[]byte", nil
	case "uuid":
		return "[16]byte", nil
	case "digest256":
		return "[32]byte", nil
	}
	if inner, ok := wrapped(value, "ref"); ok {
		if _, exists := types[inner]; exists {
			return "*" + exported(inner) + "Input", nil
		}
	}
	if inner, ok := wrapped(value, "vec"); ok {
		element, err := goInputType(inner, types)
		if err != nil {
			return "", err
		}
		return "[]" + element, nil
	}
	if _, exists := types[value]; exists {
		return exported(value) + "Input", nil
	}
	if strings.HasPrefix(value, "array<") {
		return "[]byte", nil
	}
	return "", fmt.Errorf("unsupported input type %q", value)
}

func emitGoField(out *bytes.Buffer, owner string, field schema.ResolvedField, types map[string]schema.ResolvedType) error {
	name := exported(field.Name)
	offset := field.Offset
	if goType, method, ok := scalar(field.Type); ok {
		fmt.Fprintf(out, "func (v %sView) %s() (%s, error) { return v.record.%s(%d) }\n", owner, name, goType, method, offset)
		fmt.Fprintf(out, "func (v %sView) Set%s(value %s) error { return v.record.Set%s(%d, value) }\n\n", owner, name, goType, method, offset)
		return nil
	}
	if field.Type == "utf8" || field.Type == "bytes" {
		fmt.Fprintf(out, "func (v %sView) %s() (bindas.SpanView, error) { return v.record.RegionSpan(%d) }\n", owner, name, offset)
		fmt.Fprintf(out, "func (v %sView) Set%s(value bindas.Span) error { return v.record.SetRegionSpan(%d, value) }\n", owner, name, offset)
		if field.Type == "utf8" {
			fmt.Fprintf(out, "func (v %sView) %sUTF8() (bindas.UTF8View, error) { value, err := v.%s(); if err != nil { return bindas.UTF8View{}, err }; return value.UTF8() }\n", owner, name, name)
			fmt.Fprintf(out, "func (v %sView) Set%sString(arena *bindas.Arena, value string) error { span, err := arena.PutUTF8(value); if err != nil { return err }; return v.Set%s(span) }\n\n", owner, name, name)
		} else {
			fmt.Fprintf(out, "func (v %sView) Set%sBytes(arena *bindas.Arena, value []byte) error { span, err := arena.PutBytes(value, 1); if err != nil { return err }; return v.Set%s(span) }\n\n", owner, name, name)
		}
		return nil
	}
	if inner, ok := wrapped(field.Type, "vec"); ok {
		shape, exists := generatorShape(inner, types)
		if !exists {
			return fmt.Errorf("vector element %q is not a record", inner)
		}
		fmt.Fprintf(out, "func (v %sView) %s() (bindas.Vector, error) { return v.record.RegionVector(%d, %d, %d) }\n", owner, name, offset, shape.Size, shape.Align)
		fmt.Fprintf(out, "func (v %sView) Reserve%s(arena *bindas.Arena, capacity uint32) (bindas.Vector, error) { return arena.GrowVector(v.Offset(), %d, %d, %d, capacity) }\n\n", owner, name, offset, shape.Size, shape.Align)
		if _, isRecord := types[inner]; isRecord {
			fmt.Fprintf(out, "func (v %sView) %sAt(index uint32) (%sView, error) { vector, err := v.%s(); if err != nil { return %sView{}, err }; record, err := vector.At(index); return %sView{record: record}, err }\n", owner, name, exported(inner), name, exported(inner), exported(inner))
			fmt.Fprintf(out, "func (v %sView) Append%s() (%sView, error) { vector, err := v.%s(); if err != nil { return %sView{}, err }; record, err := vector.Append(); return %sView{record: record}, err }\n\n", owner, name, exported(inner), name, exported(inner), exported(inner))
		}
		return nil
	}
	if inner, ok := wrapped(field.Type, "ref"); ok {
		if _, exists := types[inner]; !exists {
			return fmt.Errorf("reference target %q is not a record", inner)
		}
		fmt.Fprintf(out, "func (v %sView) %s(region bindas.Region) (%sView, error) { offset, err := v.record.Uint32(%d); if err != nil { return %sView{}, err }; return Open%s(region, bindas.Offset(offset)) }\n", owner, name, exported(inner), offset, exported(inner), exported(inner))
		fmt.Fprintf(out, "func (v %sView) Set%s(value %sView) error { return v.record.SetUint32(%d, uint32(value.Offset())) }\n\n", owner, name, exported(inner), offset)
		return nil
	}
	if nested, exists := types[field.Type]; exists {
		fmt.Fprintf(out, "func (v %sView) %s(region bindas.Region) (%sView, error) { return Open%s(region, v.Offset()+%d) }\n\n", owner, name, exported(nested.Name), exported(nested.Name), offset)
		return nil
	}
	if field.Type == "uuid" || field.Type == "digest256" || strings.HasPrefix(field.Type, "array<") {
		fmt.Fprintf(out, "func (v %sView) %s() ([]byte, error) { return v.record.FieldBytes(%d, %d, %d) }\n", owner, name, offset, field.Size, field.Align)
		fmt.Fprintf(out, "func (v %sView) Mutable%s() ([]byte, error) { return v.record.MutableFieldBytes(%d, %d, %d) }\n\n", owner, name, offset, field.Size, field.Align)
		return nil
	}
	return fmt.Errorf("unsupported generated field type %q", field.Type)
}

func generatorShape(name string, types map[string]schema.ResolvedType) (schema.ResolvedType, bool) {
	if typ, ok := types[name]; ok {
		return typ, true
	}
	var size, align uint32
	switch name {
	case "bool", "i8", "u8":
		size, align = 1, 1
	case "i16", "u16":
		size, align = 2, 2
	case "i32", "u32", "f32":
		size, align = 4, 4
	case "i64", "u64", "f64", "timestamp_ns", "duration_ns":
		size, align = 8, 8
	case "utf8", "bytes":
		size, align = 8, 4
	default:
		return schema.ResolvedType{}, false
	}
	return schema.ResolvedType{Size: size, Align: align}, true
}

func AssemblyScript(manifest schema.Manifest) ([]byte, error) {
	fingerprint, err := hex.DecodeString(manifest.Fingerprint)
	if err != nil || len(fingerprint) != 16 {
		return nil, fmt.Errorf("invalid manifest fingerprint %q", manifest.Fingerprint)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by wago-bind-as; DO NOT EDIT.\n")
	out.WriteString("// Accessors are allocation-free and offsets are region-relative.\n\n")
	out.WriteString("// These values compare directly with load<u64> at envelope offsets 16 and 24.\n")
	fmt.Fprintf(&out, "export const SCHEMA_FINGERPRINT_0: u64 = 0x%016x;\n", binary.LittleEndian.Uint64(fingerprint[:8]))
	fmt.Fprintf(&out, "export const SCHEMA_FINGERPRINT_1: u64 = 0x%016x;\n\n", binary.LittleEndian.Uint64(fingerprint[8:]))
	out.WriteString(`function __wbasVectorAt(base: usize, length: u32, descriptor: usize, stride: u32, alignment: u32, index: u32): u32 {
  if (descriptor > length || 12 > length - <u32>descriptor || stride == 0 || alignment == 0 || (alignment & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const offset = load<u32>(base + descriptor);
  const count = load<u32>(base + descriptor + 4);
  const capacity = load<u32>(base + descriptor + 8);
  const bytes = <u64>capacity * stride;
  if (count > capacity || bytes > u32.MAX_VALUE || offset > length || <u32>bytes > length - offset || (offset & (alignment - 1)) != 0 || index >= count) return u32.MAX_VALUE;
  return offset + index * stride;
}

function __wbasVectorAppend(base: usize, length: u32, descriptor: usize, stride: u32, alignment: u32): u32 {
  if (descriptor > length || 12 > length - <u32>descriptor || stride == 0 || alignment == 0 || (alignment & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const offset = load<u32>(base + descriptor);
  const count = load<u32>(base + descriptor + 4);
  const capacity = load<u32>(base + descriptor + 8);
  const bytes = <u64>capacity * stride;
  if (count >= capacity || bytes > u32.MAX_VALUE || offset > length || <u32>bytes > length - offset || (offset & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const item = offset + count * stride;
  memory.fill(base + item, 0, stride);
  store<u32>(base + descriptor + 4, count + 1);
  return item;
}

`)
	types := make(map[string]schema.ResolvedType, len(manifest.Types))
	for _, typ := range manifest.Types {
		types[typ.Name] = typ
	}
	for _, typ := range manifest.Types {
		name := exported(typ.Name)
		fmt.Fprintf(&out, "export namespace %s {\n  export const SIZE: u32 = %d;\n  export const ALIGN: u32 = %d;\n", name, typ.Size, typ.Align)
		fmt.Fprintf(&out, "  @inline export function valid(length: u32, offset: u32): bool { return offset <= length && SIZE <= length - offset; }\n")
		for _, field := range typ.Fields {
			if err := emitASField(&out, field, types); err != nil {
				return nil, err
			}
		}
		out.WriteString("}\n\n")
	}
	output := bytes.TrimRight(out.Bytes(), "\n")
	return append(output, '\n'), nil
}

func goByteList(value []byte) string {
	parts := make([]string, len(value))
	for i, b := range value {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	return strings.Join(parts, ", ")
}

func emitASField(out *bytes.Buffer, field schema.ResolvedField, types map[string]schema.ResolvedType) error {
	name := field.Name
	offset := field.Offset
	if _, _, ok := scalar(field.Type); ok {
		asType := field.Type
		if asType == "bool" {
			asType = "bool"
		}
		if field.Type == "timestamp_ns" || field.Type == "duration_ns" {
			asType = "i64"
		}
		fmt.Fprintf(out, "  @inline export function %s(base: usize, offset: u32): %s { return load<%s>(base + offset + %d); }\n", name, asType, asType, offset)
		fmt.Fprintf(out, "  @inline export function set%s(base: usize, offset: u32, value: %s): void { store<%s>(base + offset + %d, value); }\n", exported(name), asType, asType, offset)
		return nil
	}
	if field.Type == "utf8" || field.Type == "bytes" {
		fmt.Fprintf(out, "  @inline export function %s(base: usize, offset: u32): u64 { return load<u64>(base + offset + %d); }\n", name, offset)
		fmt.Fprintf(out, "  @inline export function set%s(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + %d, value); }\n", exported(name), offset)
		return nil
	}
	if inner, ok := wrapped(field.Type, "vec"); ok {
		shape, exists := generatorShape(inner, types)
		if !exists {
			return fmt.Errorf("vector element %q is unknown", inner)
		}
		fmt.Fprintf(out, "  @inline export function %sDescriptor(offset: u32): usize { return offset + %d; }\n", name, offset)
		fmt.Fprintf(out, "  @inline export function %sAt(base: usize, length: u32, offset: u32, index: u32): u32 { return __wbasVectorAt(base, length, %sDescriptor(offset), %d, %d, index); }\n", name, name, shape.Size, shape.Align)
		fmt.Fprintf(out, "  @inline export function append%s(base: usize, length: u32, offset: u32): u32 { return __wbasVectorAppend(base, length, %sDescriptor(offset), %d, %d); }\n", exported(name), name, shape.Size, shape.Align)
		return nil
	}
	if _, ok := wrapped(field.Type, "ref"); ok {
		fmt.Fprintf(out, "  @inline export function %s(base: usize, offset: u32): u32 { return load<u32>(base + offset + %d); }\n", name, offset)
		fmt.Fprintf(out, "  @inline export function set%s(base: usize, offset: u32, value: u32): void { store<u32>(base + offset + %d, value); }\n", exported(name), offset)
		return nil
	}
	// Inline records and fixed arrays are addressed directly.
	fmt.Fprintf(out, "  @inline export function %sOffset(offset: u32): u32 { return offset + %d; }\n", name, offset)
	return nil
}

var identifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func exported(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
func wrapped(value, kind string) (string, bool) {
	prefix := kind + "<"
	if strings.HasPrefix(value, prefix) && strings.HasSuffix(value, ">") {
		inner := strings.TrimSpace(value[len(prefix) : len(value)-1])
		return inner, inner != ""
	}
	return "", false
}
func scalar(value string) (goType, method string, ok bool) {
	switch value {
	case "bool":
		return "bool", "Bool", true
	case "i8":
		return "int8", "Int8", true
	case "u8":
		return "uint8", "Uint8", true
	case "i16":
		return "int16", "Int16", true
	case "u16":
		return "uint16", "Uint16", true
	case "i32":
		return "int32", "Int32", true
	case "u32":
		return "uint32", "Uint32", true
	case "i64", "timestamp_ns", "duration_ns":
		return "int64", "Int64", true
	case "u64":
		return "uint64", "Uint64", true
	case "f32":
		return "float32", "Float32", true
	case "f64":
		return "float64", "Float64", true
	default:
		return "", "", false
	}
}
