// Code generated by wago-bind-as; DO NOT EDIT.
// Accessors are allocation-free and offsets are region-relative.

// These values compare directly with load<u64> at envelope offsets 16 and 24.
export const SCHEMA_FINGERPRINT_0: u64 = 0x3f532180cb592be4;
export const SCHEMA_FINGERPRINT_1: u64 = 0xf9a01dc3ed10c560;

function __wbasVectorAt(base: usize, length: u32, descriptor: usize, stride: u32, alignment: u32, index: u32): u32 {
  if (descriptor > length || 12 > length - <u32>descriptor || stride == 0 || alignment == 0 || (alignment & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const offset = load<u32>(base + descriptor);
  const count = load<u32>(base + descriptor + 4);
  const capacity = load<u32>(base + descriptor + 8);
  const bytes = <u64>capacity * stride;
  if (count > capacity || bytes > u32.MAX_VALUE || offset > length || <u32>bytes > length - offset || (offset & (alignment - 1)) != 0 || index >= count) return u32.MAX_VALUE;
  return offset + index * stride;
}

function __wbasVectorAppend(base: usize, length: u32, descriptor: usize, stride: u32, alignment: u32): u32 {
  if (descriptor > length || 12 > length - <u32>descriptor || stride == 0 || alignment == 0 || (alignment & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const offset = load<u32>(base + descriptor);
  const count = load<u32>(base + descriptor + 4);
  const capacity = load<u32>(base + descriptor + 8);
  const bytes = <u64>capacity * stride;
  if (count >= capacity || bytes > u32.MAX_VALUE || offset > length || <u32>bytes > length - offset || (offset & (alignment - 1)) != 0) return u32.MAX_VALUE;
  const item = offset + count * stride;
  memory.fill(base + item, 0, stride);
  store<u32>(base + descriptor + 4, count + 1);
  return item;
}

export namespace Header {
  export const SIZE: u32 = 16;
  export const ALIGN: u32 = 4;
  @inline export function valid(length: u32, offset: u32): bool { return offset <= length && SIZE <= length - offset; }
  @inline export function name(base: usize, offset: u32): u64 { return load<u64>(base + offset + 0); }
  @inline export function setName(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 0, value); }
  @inline export function value(base: usize, offset: u32): u64 { return load<u64>(base + offset + 8); }
  @inline export function setValue(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 8, value); }
}

export namespace Request {
  export const SIZE: u32 = 56;
  export const ALIGN: u32 = 8;
  @inline export function valid(length: u32, offset: u32): bool { return offset <= length && SIZE <= length - offset; }
  @inline export function id(base: usize, offset: u32): u64 { return load<u64>(base + offset + 0); }
  @inline export function setId(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 0, value); }
  @inline export function score(base: usize, offset: u32): f32 { return load<f32>(base + offset + 8); }
  @inline export function setScore(base: usize, offset: u32, value: f32): void { store<f32>(base + offset + 8, value); }
  @inline export function flags(base: usize, offset: u32): u32 { return load<u32>(base + offset + 12); }
  @inline export function setFlags(base: usize, offset: u32, value: u32): void { store<u32>(base + offset + 12, value); }
  @inline export function name(base: usize, offset: u32): u64 { return load<u64>(base + offset + 16); }
  @inline export function setName(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 16, value); }
  @inline export function body(base: usize, offset: u32): u64 { return load<u64>(base + offset + 24); }
  @inline export function setBody(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 24, value); }
  @inline export function headersDescriptor(offset: u32): usize { return offset + 32; }
  @inline export function headersAt(base: usize, length: u32, offset: u32, index: u32): u32 { return __wbasVectorAt(base, length, headersDescriptor(offset), 16, 4, index); }
  @inline export function appendHeaders(base: usize, length: u32, offset: u32): u32 { return __wbasVectorAppend(base, length, headersDescriptor(offset), 16, 4); }
  @inline export function user(base: usize, offset: u32): u32 { return load<u32>(base + offset + 44); }
  @inline export function setUser(base: usize, offset: u32, value: u32): void { store<u32>(base + offset + 44, value); }
  @inline export function timestamp(base: usize, offset: u32): i64 { return load<i64>(base + offset + 48); }
  @inline export function setTimestamp(base: usize, offset: u32, value: i64): void { store<i64>(base + offset + 48, value); }
}

export namespace User {
  export const SIZE: u32 = 16;
  export const ALIGN: u32 = 8;
  @inline export function valid(length: u32, offset: u32): bool { return offset <= length && SIZE <= length - offset; }
  @inline export function id(base: usize, offset: u32): u64 { return load<u64>(base + offset + 0); }
  @inline export function setId(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 0, value); }
  @inline export function name(base: usize, offset: u32): u64 { return load<u64>(base + offset + 8); }
  @inline export function setName(base: usize, offset: u32, value: u64): void { store<u64>(base + offset + 8, value); }
}
