// Code generated by wago-bind-as; DO NOT EDIT.

package request

import bindas "github.com/JairusSW/wago-bind-as"

const SchemaFingerprintHex = "e42b59cb8021533f60c510edc31da0f9"

func Fingerprint() bindas.Fingerprint {
	return bindas.Fingerprint{0xe4, 0x2b, 0x59, 0xcb, 0x80, 0x21, 0x53, 0x3f, 0x60, 0xc5, 0x10, 0xed, 0xc3, 0x1d, 0xa0, 0xf9}
}

const (
	HeaderSize  uint32 = 16
	HeaderAlign uint32 = 4
)

type HeaderView struct{ record bindas.Record }

func OpenHeader(region bindas.Region, offset bindas.Offset) (HeaderView, error) {
	record, err := region.Record(offset, HeaderSize, HeaderAlign)
	return HeaderView{record: record}, err
}

func NewHeader(arena *bindas.Arena) (HeaderView, error) {
	offset, err := arena.Alloc(HeaderSize, HeaderAlign)
	if err != nil {
		return HeaderView{}, err
	}
	return OpenHeader(arena.Region(), offset)
}

func (v HeaderView) Offset() bindas.Offset { return v.record.Offset() }

func (v HeaderView) Name() (bindas.SpanView, error)  { return v.record.RegionSpan(0) }
func (v HeaderView) SetName(value bindas.Span) error { return v.record.SetRegionSpan(0, value) }
func (v HeaderView) NameUTF8() (bindas.UTF8View, error) {
	value, err := v.Name()
	if err != nil {
		return bindas.UTF8View{}, err
	}
	return value.UTF8()
}
func (v HeaderView) SetNameString(arena *bindas.Arena, value string) error {
	span, err := arena.PutUTF8(value)
	if err != nil {
		return err
	}
	return v.SetName(span)
}

func (v HeaderView) Value() (bindas.SpanView, error)  { return v.record.RegionSpan(8) }
func (v HeaderView) SetValue(value bindas.Span) error { return v.record.SetRegionSpan(8, value) }
func (v HeaderView) ValueUTF8() (bindas.UTF8View, error) {
	value, err := v.Value()
	if err != nil {
		return bindas.UTF8View{}, err
	}
	return value.UTF8()
}
func (v HeaderView) SetValueString(arena *bindas.Arena, value string) error {
	span, err := arena.PutUTF8(value)
	if err != nil {
		return err
	}
	return v.SetValue(span)
}

type Header struct {
	Name  string
	Value string
}

type HeaderInput = Header

func BuildHeader(arena *bindas.Arena, value HeaderInput) (HeaderView, error) {
	checkpoint := arena.Checkpoint()
	view, err := NewHeader(arena)
	if err != nil {
		return HeaderView{}, err
	}
	if err = fillHeader(arena, view, value); err != nil {
		_ = arena.Rollback(checkpoint)
		return HeaderView{}, err
	}
	return view, nil
}

func fillHeader(arena *bindas.Arena, view HeaderView, value HeaderInput) error {
	if err := view.SetNameString(arena, value.Name); err != nil {
		return err
	}
	if err := view.SetValueString(arena, value.Value); err != nil {
		return err
	}
	return nil
}

const (
	RequestSize  uint32 = 56
	RequestAlign uint32 = 8
)

type RequestView struct{ record bindas.Record }

func OpenRequest(region bindas.Region, offset bindas.Offset) (RequestView, error) {
	record, err := region.Record(offset, RequestSize, RequestAlign)
	return RequestView{record: record}, err
}

func NewRequest(arena *bindas.Arena) (RequestView, error) {
	offset, err := arena.Alloc(RequestSize, RequestAlign)
	if err != nil {
		return RequestView{}, err
	}
	return OpenRequest(arena.Region(), offset)
}

func (v RequestView) Offset() bindas.Offset { return v.record.Offset() }

func (v RequestView) Id() (uint64, error)      { return v.record.Uint64(0) }
func (v RequestView) SetId(value uint64) error { return v.record.SetUint64(0, value) }

func (v RequestView) Score() (float32, error)      { return v.record.Float32(8) }
func (v RequestView) SetScore(value float32) error { return v.record.SetFloat32(8, value) }

func (v RequestView) Flags() (uint32, error)      { return v.record.Uint32(12) }
func (v RequestView) SetFlags(value uint32) error { return v.record.SetUint32(12, value) }

func (v RequestView) Name() (bindas.SpanView, error)  { return v.record.RegionSpan(16) }
func (v RequestView) SetName(value bindas.Span) error { return v.record.SetRegionSpan(16, value) }
func (v RequestView) NameUTF8() (bindas.UTF8View, error) {
	value, err := v.Name()
	if err != nil {
		return bindas.UTF8View{}, err
	}
	return value.UTF8()
}
func (v RequestView) SetNameString(arena *bindas.Arena, value string) error {
	span, err := arena.PutUTF8(value)
	if err != nil {
		return err
	}
	return v.SetName(span)
}

func (v RequestView) Body() (bindas.SpanView, error)  { return v.record.RegionSpan(24) }
func (v RequestView) SetBody(value bindas.Span) error { return v.record.SetRegionSpan(24, value) }
func (v RequestView) SetBodyBytes(arena *bindas.Arena, value []byte) error {
	span, err := arena.PutBytes(value, 1)
	if err != nil {
		return err
	}
	return v.SetBody(span)
}

func (v RequestView) Headers() (bindas.Vector, error) { return v.record.RegionVector(32, 16, 4) }
func (v RequestView) ReserveHeaders(arena *bindas.Arena, capacity uint32) (bindas.Vector, error) {
	return arena.GrowVector(v.Offset(), 32, 16, 4, capacity)
}

func (v RequestView) HeadersAt(index uint32) (HeaderView, error) {
	vector, err := v.Headers()
	if err != nil {
		return HeaderView{}, err
	}
	record, err := vector.At(index)
	return HeaderView{record: record}, err
}
func (v RequestView) AppendHeaders() (HeaderView, error) {
	vector, err := v.Headers()
	if err != nil {
		return HeaderView{}, err
	}
	record, err := vector.Append()
	return HeaderView{record: record}, err
}

func (v RequestView) User(region bindas.Region) (UserView, error) {
	offset, err := v.record.Uint32(44)
	if err != nil {
		return UserView{}, err
	}
	return OpenUser(region, bindas.Offset(offset))
}
func (v RequestView) SetUser(value UserView) error {
	return v.record.SetUint32(44, uint32(value.Offset()))
}

func (v RequestView) Timestamp() (int64, error)      { return v.record.Int64(48) }
func (v RequestView) SetTimestamp(value int64) error { return v.record.SetInt64(48, value) }

type Request struct {
	Id        uint64
	Score     float32
	Flags     uint32
	Name      string
	Body      []byte
	Headers   []HeaderInput
	User      *UserInput
	Timestamp int64
}

type RequestInput = Request

func BuildRequest(arena *bindas.Arena, value RequestInput) (RequestView, error) {
	checkpoint := arena.Checkpoint()
	view, err := NewRequest(arena)
	if err != nil {
		return RequestView{}, err
	}
	if err = fillRequest(arena, view, value); err != nil {
		_ = arena.Rollback(checkpoint)
		return RequestView{}, err
	}
	return view, nil
}

func fillRequest(arena *bindas.Arena, view RequestView, value RequestInput) error {
	if err := view.SetId(value.Id); err != nil {
		return err
	}
	if err := view.SetScore(value.Score); err != nil {
		return err
	}
	if err := view.SetFlags(value.Flags); err != nil {
		return err
	}
	if err := view.SetNameString(arena, value.Name); err != nil {
		return err
	}
	if err := view.SetBodyBytes(arena, value.Body); err != nil {
		return err
	}
	if uint64(len(value.Headers)) > uint64(^uint32(0)) {
		return bindas.ErrOutOfSpace
	}
	headersVector, err := view.ReserveHeaders(arena, uint32(len(value.Headers)))
	if err != nil {
		return err
	}
	for _, item := range value.Headers {
		record, err := headersVector.Append()
		if err != nil {
			return err
		}
		if err = fillHeader(arena, HeaderView{record: record}, item); err != nil {
			return err
		}
	}
	if value.User == nil {
		return bindas.ErrMalformed
	}
	userValue, err := BuildUser(arena, *value.User)
	if err != nil {
		return err
	}
	if err = view.SetUser(userValue); err != nil {
		return err
	}
	if err := view.SetTimestamp(value.Timestamp); err != nil {
		return err
	}
	return nil
}

const (
	UserSize  uint32 = 16
	UserAlign uint32 = 8
)

type UserView struct{ record bindas.Record }

func OpenUser(region bindas.Region, offset bindas.Offset) (UserView, error) {
	record, err := region.Record(offset, UserSize, UserAlign)
	return UserView{record: record}, err
}

func NewUser(arena *bindas.Arena) (UserView, error) {
	offset, err := arena.Alloc(UserSize, UserAlign)
	if err != nil {
		return UserView{}, err
	}
	return OpenUser(arena.Region(), offset)
}

func (v UserView) Offset() bindas.Offset { return v.record.Offset() }

func (v UserView) Id() (uint64, error)      { return v.record.Uint64(0) }
func (v UserView) SetId(value uint64) error { return v.record.SetUint64(0, value) }

func (v UserView) Name() (bindas.SpanView, error)  { return v.record.RegionSpan(8) }
func (v UserView) SetName(value bindas.Span) error { return v.record.SetRegionSpan(8, value) }
func (v UserView) NameUTF8() (bindas.UTF8View, error) {
	value, err := v.Name()
	if err != nil {
		return bindas.UTF8View{}, err
	}
	return value.UTF8()
}
func (v UserView) SetNameString(arena *bindas.Arena, value string) error {
	span, err := arena.PutUTF8(value)
	if err != nil {
		return err
	}
	return v.SetName(span)
}

type User struct {
	Id   uint64
	Name string
}

type UserInput = User

func BuildUser(arena *bindas.Arena, value UserInput) (UserView, error) {
	checkpoint := arena.Checkpoint()
	view, err := NewUser(arena)
	if err != nil {
		return UserView{}, err
	}
	if err = fillUser(arena, view, value); err != nil {
		_ = arena.Rollback(checkpoint)
		return UserView{}, err
	}
	return view, nil
}

func fillUser(arena *bindas.Arena, view UserView, value UserInput) error {
	if err := view.SetId(value.Id); err != nil {
		return err
	}
	if err := view.SetNameString(arena, value.Name); err != nil {
		return err
	}
	return nil
}
