package gobind

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestSyncGeneratesStableAssemblyScript(t *testing.T) {
	root := t.TempDir()
	source := `package model

//wago:bind assembly/models.bind.ts
type Vec3 struct {
	X float32
	Y float32
	Z float32 ` + "`wago:\"depth\"`" + `
}
`
	if err := os.WriteFile(filepath.Join(root, "models.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	changed, err := Sync(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(changed) != 1 {
		t.Fatalf("changed = %v", changed)
	}
	target := filepath.Join(root, "assembly", "models.bind.ts")
	contents, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	for _, fragment := range []string{"Code generated by wago-bind-as", "Source fingerprint:", "export class Vec3", "x: f32", "depth: f32", "constructor("} {
		if !strings.Contains(string(contents), fragment) {
			t.Fatalf("generated file is missing %q:\n%s", fragment, contents)
		}
	}
	info, _ := os.Stat(target)
	time.Sleep(time.Millisecond)
	changed, err = Sync(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(changed) != 0 {
		t.Fatalf("unchanged sync rewrote %v", changed)
	}
	after, _ := os.Stat(target)
	if !after.ModTime().Equal(info.ModTime()) {
		t.Fatal("unchanged generated file was rewritten")
	}
}

func TestSyncRefusesToOverwriteHandwrittenFile(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "models.go"), []byte("package model\n//wago:bind models.bind.ts\ntype Model struct { Value uint32 }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "models.bind.ts"), []byte("export class Mine {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Sync(root); err == nil {
		t.Fatal("Sync overwrote a handwritten target")
	}
}
