// Package gobind extracts explicitly shared Go structs into ordinary,
// IntelliSense-friendly AssemblyScript source files.
package gobind

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const generatedMarker = "// Code generated by wago-bind-as. DO NOT EDIT."
const generatorVersion = "0.1.0"

type wireType struct {
	Name   string
	Source string
	Fields []wireField
}

type wireField struct {
	GoName string
	ASName string
	Type   string
}

// Sync scans root for //wago:bind <target.bind.ts> declarations and updates
// every generated target atomically. It returns the paths that changed.
func Sync(root string) ([]string, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	groups := make(map[string][]wireType)
	err = filepath.WalkDir(absRoot, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			switch entry.Name() {
			case ".git", "build", "node_modules", "vendor":
				if path != absRoot {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, ".bind.go") {
			return nil
		}
		matched, err := build.Default.MatchFile(filepath.Dir(path), entry.Name())
		if err != nil {
			return err
		}
		if !matched {
			return nil
		}
		return scanFile(absRoot, path, groups)
	})
	if err != nil {
		return nil, err
	}
	targets := make([]string, 0, len(groups))
	for target := range groups {
		targets = append(targets, target)
	}
	sort.Strings(targets)
	changed := make([]string, 0, len(targets))
	for _, target := range targets {
		types := groups[target]
		sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })
		contents, err := render(target, types)
		if err != nil {
			return nil, err
		}
		updated, err := writeGenerated(target, contents)
		if err != nil {
			return nil, err
		}
		if updated {
			changed = append(changed, target)
		}
	}
	return changed, nil
}

func scanFile(root, path string, groups map[string][]wireType) error {
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, path, nil, parser.ParseComments)
	if err != nil {
		return err
	}
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, spec := range general.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			target, ok := bindTarget(typeSpec.Doc, general.Doc)
			if !ok {
				continue
			}
			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				return fmt.Errorf("%s: //wago:bind type %s must be a struct", path, typeSpec.Name.Name)
			}
			if filepath.Ext(target) != ".ts" || !strings.HasSuffix(target, ".bind.ts") {
				return fmt.Errorf("%s: //wago:bind target %q must end in .bind.ts", path, target)
			}
			if !filepath.IsAbs(target) {
				target = filepath.Join(root, filepath.FromSlash(target))
			}
			fields := make([]wireField, 0, len(structure.Fields.List))
			for _, field := range structure.Fields.List {
				if len(field.Names) != 1 || !field.Names[0].IsExported() {
					return fmt.Errorf("%s: bound struct %s requires named exported fields", path, typeSpec.Name.Name)
				}
				wire, err := goType(field.Type)
				if err != nil {
					return fmt.Errorf("%s: %s.%s: %w", path, typeSpec.Name.Name, field.Names[0].Name, err)
				}
				asName := lowerFirst(field.Names[0].Name)
				if field.Tag != nil {
					if tagged := strings.Split(reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("wago"), ",")[0]; tagged != "" && tagged != "-" {
						asName = tagged
					}
				}
				fields = append(fields, wireField{GoName: field.Names[0].Name, ASName: asName, Type: wire})
			}
			if len(fields) == 0 {
				return fmt.Errorf("%s: bound struct %s has no fields", path, typeSpec.Name.Name)
			}
			relative, _ := filepath.Rel(root, path)
			groups[target] = append(groups[target], wireType{Name: typeSpec.Name.Name, Source: filepath.ToSlash(relative), Fields: fields})
		}
	}
	return nil
}

func bindTarget(groups ...*ast.CommentGroup) (string, bool) {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
			if strings.HasPrefix(text, "wago:bind ") {
				target := strings.TrimSpace(strings.TrimPrefix(text, "wago:bind "))
				return target, target != ""
			}
		}
	}
	return "", false
}

func goType(expression ast.Expr) (string, error) {
	identifier, ok := expression.(*ast.Ident)
	if !ok {
		return "", fmt.Errorf("only scalar fields are currently supported")
	}
	switch identifier.Name {
	case "bool":
		return "bool", nil
	case "int8", "uint8", "byte", "int16", "uint16", "int32", "rune", "uint32", "int64", "uint64", "float32", "float64":
		return map[string]string{"int8": "i8", "uint8": "u8", "byte": "u8", "int16": "i16", "uint16": "u16", "int32": "i32", "rune": "i32", "uint32": "u32", "int64": "i64", "uint64": "u64", "float32": "f32", "float64": "f64"}[identifier.Name], nil
	default:
		return "", fmt.Errorf("unsupported Go type %s", identifier.Name)
	}
}

func render(target string, types []wireType) ([]byte, error) {
	canonical := new(bytes.Buffer)
	canonical.WriteString(generatorVersion)
	seenTypes := make(map[string]struct{}, len(types))
	for _, typ := range types {
		if _, exists := seenTypes[typ.Name]; exists {
			return nil, fmt.Errorf("duplicate bound type %s for %s", typ.Name, target)
		}
		seenTypes[typ.Name] = struct{}{}
		fmt.Fprintf(canonical, "%s:%s;", typ.Source, typ.Name)
		seenFields := make(map[string]struct{}, len(typ.Fields))
		for _, field := range typ.Fields {
			if _, exists := seenFields[field.ASName]; exists {
				return nil, fmt.Errorf("bound type %s has duplicate AssemblyScript field %s", typ.Name, field.ASName)
			}
			seenFields[field.ASName] = struct{}{}
			fmt.Fprintf(canonical, "%s:%s:%s;", field.GoName, field.ASName, field.Type)
		}
	}
	sum := sha256.Sum256(canonical.Bytes())
	var output bytes.Buffer
	fmt.Fprintln(&output, generatedMarker)
	fmt.Fprintf(&output, "// Generator: %s\n", generatorVersion)
	fmt.Fprintf(&output, "// Source fingerprint: %s\n", hex.EncodeToString(sum[:16]))
	fmt.Fprintln(&output)
	for _, typ := range types {
		fmt.Fprintf(&output, "// Source: %s\n@unmanaged\nexport class %s {\n", typ.Source, typ.Name)
		for _, field := range typ.Fields {
			fmt.Fprintf(&output, "  %s: %s;\n", field.ASName, field.Type)
		}
		output.WriteString("\n  constructor(")
		for i, field := range typ.Fields {
			if i != 0 {
				output.WriteString(", ")
			}
			fmt.Fprintf(&output, "%s: %s = %s", field.ASName, field.Type, asDefault(field.Type))
		}
		output.WriteString(") {\n")
		for _, field := range typ.Fields {
			fmt.Fprintf(&output, "    this.%s = %s;\n", field.ASName, field.ASName)
		}
		output.WriteString("  }\n}\n\n")
	}
	return output.Bytes(), nil
}

func asDefault(typ string) string {
	if typ == "bool" {
		return "false"
	}
	return "0"
}

func writeGenerated(target string, contents []byte) (bool, error) {
	existing, err := os.ReadFile(target)
	if err == nil {
		if bytes.Equal(existing, contents) {
			return false, nil
		}
		if !bytes.HasPrefix(existing, []byte(generatedMarker)) {
			return false, fmt.Errorf("refusing to overwrite non-generated file %s", target)
		}
	} else if !os.IsNotExist(err) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return false, err
	}
	temporary, err := os.CreateTemp(filepath.Dir(target), ".wago-bind-as-*.tmp")
	if err != nil {
		return false, err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if err = temporary.Chmod(0o644); err == nil {
		_, err = temporary.Write(contents)
	}
	if err == nil {
		err = temporary.Sync()
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err == nil {
		err = os.Rename(name, target)
	}
	return err == nil, err
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = []rune(strings.ToLower(string(runes[0])))[0]
	return string(runes)
}
